# Generated by Django 5.0.6 on 2024-07-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuaruio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='usuaruio',
            new_name='usuario',
        ),
    ]
